nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173'] # Cambia esto según tu puerto de Vue
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
